### ISSUE TITLE
yolov2-keras- axes don't match array

### ISSUE THREAD

**Issue by AsyDynamics** [AsyDynamics/CS231n#2]
The demo in original repo (https://github.com/experiencor/keras-yolo2) is in python2. I installed the necessary library of python3 and try to run prediction:
python3 predict.py -c config.json -w mobilenet_raccoon.h5 -i images/dog.jpg

But get such error:

Total params: 3,259,614
Trainable params: 3,237,726
Non-trainable params: 21,888
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "predict.py", line 96, in <module>
    _main_(args)
  File "predict.py", line 56, in _main_
    yolo.load_weights(weights_path)
  File "/home/pi/CNN/keras-yolo2/frontend.py", line 243, in load_weights
    self.model.load_weights(weight_path)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 916, in load_weights_from_hdf5_group
    reshape=reshape)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 557, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 545, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 557, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 533, in convert_nested_model
    original_backend=original_backend))
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 675, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 575, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

The config json file is:
{
    "model" : {
        "backend":              "MobileNet",
        "input_size":           416,
        "anchors":              [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828],
        "max_box_per_image":    10,        
        "labels":               ["raccoon"]
    },

    "train": {
        "train_image_folder":   "/home/andy/data/kangaroo/images/",
        "train_annot_folder":   "/home/andy/data/kangaroo/annots/",     
          
        "train_times":          8,
        "pretrained_weights":   "full_yolo_kangaroo3.h5",
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epochs":            1,
        "warmup_epochs":        3,

        "object_scale":         5.0 ,
        "no_object_scale":      1.0,
        "coord_scale":          1.0,
        "class_scale":          1.0,

        "saved_weights_name":   "full_yolo_kangaroo.h5",
        "debug":                true
    },

    "valid": {
        "valid_image_folder":   "",
        "valid_annot_folder":   "",

        "valid_times":          1
    }
}

**Comment by AsyDynamics** [comment]
Use another image from https://github.com/experiencor/raccoon_dataset to predict, and get one more different error:
ValueError: axes don't match array
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x66121b50>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 707, in __del__
TypeError: 'NoneType' object is not callable
